# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LEDControl' do
  source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
pod "Colorful", "~> 3.0"
use_frameworks!

pod 'Starscream', '~> 4.0.0'

end
